name: Browser testing on browser stack

on:
  push:
    branches:
      - '*'
    tags:

# Allow only one concurrent test
concurrency:
  group: "browserstack"
  cancel-in-progress: false

jobs:
  browser-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - run: npm ci
      - run: npm run test:browserstack
        env:
          CI: true
          BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
          BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
